# Generated by Django 5.2.17 on 2026-10-06 08:53

import computes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computes", "0003_auto_20200615_0637"),
    ]

    operations = [
        migrations.AddField(
            model_name="compute",
            name="migration_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IP address or host name the other hosts send migrating VMs to; empty: the host's own host name, which they must be able to resolve",
                max_length=64,
                validators=[computes.validators.validate_migration_address],
                verbose_name="migration address",
            ),
        ),
    ]
