# Generated by Django 5.2.17 on 2026-10-06 19:07

import computes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computes", "0004_compute_migration_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compute",
            name="hostname",
            field=models.CharField(
                max_length=64,
                validators=[computes.validators.validate_hostname],
                verbose_name="hostname",
            ),
        ),
        migrations.AlterField(
            model_name="compute",
            name="login",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[computes.validators.validate_login],
                verbose_name="login",
            ),
        ),
    ]
