# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0004_auto_20180724_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'volume name', max_length=120)),
                ('source', models.CharField(help_text=b'volume file path/source', max_length=250)),
                ('type', models.CharField(help_text=b'volume type', max_length=10)),
                ('dev', models.CharField(help_text=b'device', max_length=5)),
                ('bus', models.CharField(help_text=b'volume bus', max_length=10)),
                ('storage', models.CharField(help_text=b'volume storage', max_length=50)),
                ('format', models.CharField(help_text=b'volume format', max_length=10)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instances.Instance')),
            ],
        ),
    ]
