# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-02 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0004_auto_20180724_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=25, unique=True, verbose_name=b'snapshot name')),
                ('num_disk', models.IntegerField(verbose_name=b'number of disks')),
                ('date', models.DateTimeField(verbose_name=b'creation Time')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'snapshot description')),
                ('deleted', models.BooleanField(default=False, verbose_name=b'has it deletable disks')),
                ('current', models.BooleanField(verbose_name=b'is it current snapshot')),
                ('parent', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'snapshot parent')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instances.Instance')),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snap_type', models.CharField(blank=True, max_length=15, verbose_name=b'snapshot type')),
                ('source', models.FilePathField(verbose_name=b'disk filename with path')),
                ('dev', models.CharField(max_length=5, verbose_name=b'disk dev name')),
                ('driver', models.CharField(blank=True, max_length=5, verbose_name=b'disk driver type')),
                ('parent', models.CharField(blank=True, max_length=200, verbose_name=b'disk backing file')),
                ('type', models.CharField(blank=True, max_length=5, verbose_name=b'disk type')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instances.Snapshot')),
            ],
        ),
    ]
