# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-07 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0005_disk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disk',
            name='name',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='type',
        ),
    ]
