# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-24 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0006_auto_20181221_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshotdisk',
            name='format',
        ),
        migrations.AddField(
            model_name='snapshotdisk',
            name='parent',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'disk backing file'),
        ),
    ]
