# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-24 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0007_auto_20181224_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'snapshot description'),
        ),
    ]
