# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-24 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0008_auto_20181224_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='current',
            field=models.BooleanField(verbose_name=b'is it current snapshot'),
        ),
    ]
