# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-27 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0010_auto_20181225_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='parent',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name=b'snapshot parent'),
        ),
    ]
