# Generated by Django 5.2.17 on 2026-10-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0012_instance_unique_compute_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstanceTombstone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(db_index=True, max_length=36)),
                ("name", models.CharField(max_length=120)),
                ("is_template", models.BooleanField(default=False)),
                ("owners", models.JSONField(default=list)),
                ("removed", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
